user:
  resource: user_routing.yaml
  prefix: /user

admin:
  resource: admin_routing.yaml
  prefix: /admin

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
  path: /
  controller: App\Front\Controller\HomeController::index

