
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

task_new:
    path: /newTask
    controller: App\Backoffice\Controller\TaskController::newTask

admin:
  path: /admin
  controller: App\Backoffice\Controller\AdminController::admin

adminTasks:
  path: /adminTasks
  controller: App\Backoffice\Controller\AdminController::adminTasks

task_edit:
  path: /task/{id}/edit
  controller: App\Backoffice\Controller\TaskController::edit

task_show:
  path: /task/show/{id}
  controller: App\Backoffice\Controller\TaskController::show

task_delete:
  path: /task/{id}
  controller: App\Backoffice\Controller\TaskController::delete

user_index:
  path: /
  controller: App\front\Controller\HomeController::index

selected_day:
  path: /day/{day}/{month}/{year}
  controller: App\front\Controller\TaskController::NewTaskByDay

scroll_calendar:
  path: /home/{first_day}
  controller: App\front\Controller\HomeController::home

taskfront_new:
  path: /newFrontTask
  controller: App\front\Controller\TaskController::newTaskFront
task_showUser:
  path: /taskUser/show/{id}
  controller: App\front\Controller\TaskController::show

all_tasks_by_date:
  path: /alltasks/{day}/{month}/{year}
  controller: App\front\Controller\TaskController::AllTasksByDay