user_index:
  path: /
  controller: App\Front\Controller\HomeController::index

user_new_selected_day:
  path: /day/{day}/{month}/{year}
  controller: App\Front\Controller\TaskController::newTaskByDay

scroll_calendar:
  path: /home/{first_day}
  controller: App\Front\Controller\HomeController::home

user_front_new:
  path: /new
  controller: App\Front\Controller\TaskController::newTaskFront

user_front_show:
  path: /taskUser/show/{id}
  controller: App\Front\Controller\TaskController::show

user_front_edit:
  path: /taskUser/edit/{id}
  controller: App\Front\Controller\TaskController::edit
user_front_delete:
  path: /task/delete/{id}
  controller: App\Front\Controller\TaskController::delete

show_tasks_selected_day:
  path: /task/{day}/{month}/{year}
  controller: App\Front\Controller\TaskController::taskByDay
change_approve:
  path: /approve/edit/{id}/{usertask}
  controller: App\Front\Controller\TaskController::changeApprove